Comment: A state machine to analyze document and upload results to S3
StartAt: Analyze Document
States:
  Analyze Document:
    Type: Task
    Resource: arn:aws:states:::lambda:invoke
    Parameters:
      FunctionName: 
        "${TextractFunction}"
      Payload:
        Document.$: $.Document
    Retry:
      - ErrorEquals:
          - Lambda.ServiceException
          - Lambda.AWSLambdaException
          - Lambda.SdkClientException
          - Lambda.TooManyRequestsException
        IntervalSeconds: 2
        MaxAttempts: 6
        BackoffRate: 2
    Next: PutObject
    ResultPath: $.Result
  PutObject:
    Type: Task
    End: true
    Parameters:
      Body.$: $.Result.Payload.body
      Bucket: ${OutputBucket}
      Key.$: States.Format('output/{}', $.Document)
    Resource: arn:aws:states:::aws-sdk:s3:putObject
